# 01-setup.yaml
---
  - hosts: app_event_servers_kafka
    gather_facts: no
    vars:
      var_event_servers_kafka_download: true
    tasks:
      - name: Setup Download - Include App Servers Role
        include_role:
          name: app-servers-kafka
   
  - hosts: app_event_servers_kafka
    gather_facts: no
    vars:
      var_event_servers_kafka_run: true
    tasks:
      - name: Setup Install Kafka
        include_role:
          name: app-servers-kafka
   
